
import { Metadata } from "next";
import About from "./about/page";
import Courses from "./courses/page";
import HomePage from "./home/page";
import TrainersPage from "./trainers/page";


export const metadata: Metadata= {
  title: "Project ELITE",
  description: "Generated by create next app",
};

const Main =()=>{

    return (
 <>
 <div className="flex flex-col items-center w-full bg-gradient-to-b from-white to-blue-50">
            {/* Hero Section */}
            <div className="w-full h-fit max-w-6xl px-6 mb-12">
            <HomePage/>
            </div>

 {/* trainers */}
            <div className="w-full h-fit max-w-6xl px-6 mb-12">
            <TrainersPage />
            </div>



            {/* courses */}
            <div className="w-full h-fit max-w-6xl px-6 mb-12">
            <Courses />
            </div>

            {/* About Section */}
            <div className="w-full h-fit ">
            <About />
            </div>
        </div>
        </>
    );
}

export default Main;